### ISSUE TITLE
The linter panicked unexpectedly

### ISSUE THREAD

**Issue by brandly** [RDambrosio016/RSLint#30]
hi! i saw your post on r/rust. i write a lot of typescript, but tried running this on some plain JS.

i ran it on [this file](https://github.com/brandly/js-sudoku/blob/master/index.js) and was told everything's good:
```shell
$ rslint_cli index.js

Outcome: 0 fail, 0 warn, 1 success
```

i wanted to run it on [this project](https://github.com/Sentenai/js-sentenai), but i ran into an unexpected panic.

```shell
$ rslint_cli 'src/*.js' 
error[]: The linter panicked unexpectedly. this is a bug.

We would appreciate a bug report: https://github.com/RDambrosio016/RSLint/issues/new?labels=ILE%2C+bug&template=internal-linter-error.md

note[]: Please include the following info: 

message: 
location: /Users/brandly/.cargo/registry/src/github.com-1ecc6299db9ec823/rslint_parser-0.1.2/src/parser.rs:158:9
```

i'm wrapping the glob in quotes because i'm on zsh, and it'll expand the glob otherwise e.g.:

```shell
$ rslint_cli src/*.js  
error: Found argument 'src/api.test.js' which wasn't expected, or isn't valid in this context

USAGE:
    rslint_cli [FLAGS] [files] [SUBCOMMAND]

For more information try --help
```

if i'm running this incorrectly, the feedback could be improved. otherwise, something might be broken.

thanks again. i'm looking forward to fast JS tooling.

**Comment by RDambrosio016** [comment]
Thank you for the bug report!

Im still not sure why the message is not included for that but yknow, weird rust panic info logic, but thats the parser infinitely recursing, which is usually because of:
- Bad error recovery
- Bad parsing
I will take a look and update you once i find/fix it 🙂

**Comment by RDambrosio016** [comment]
Okay i think i found the issue, the MWE for this is:

```js
let a = { a: true };
```

 the lexer is producing an error token from `a:` for some odd reason, which throws the parser for a loop because of this code:

```rust
                if prop?.kind() != NAME || p.at(T![:]) {
                    p.expect(T![:]);
                    assign_expr(p);
                    Some(m.complete(p, LITERAL_PROP))
                } else {
                    Some(m.complete(p, IDENT_PROP))
                }
```

**Comment by RDambrosio016** [comment]
Oh nevermind, the issue is the unicode character which i did not notice, like `let foo = { α: true }`. The lexer makes it an error token and the parser has a hard time recovering from there. I think this is a lexer issue since if i am not mistaken that is an allowed char for identifiers

**Comment by RDambrosio016** [comment]
This also brings to light the issue of error tokens in literal properties causing infinite recursion, which is an error recovery problem. Thank you for finding 2 bugs! 😄

**Comment by RDambrosio016** [comment]
Lexer issue fixed in https://github.com/RDambrosio016/RSLint/commit/d0dbbe9ed0dd022a985b883bdcb6ab35af265f16
Parser issue has not been fixed yet

**Comment by RDambrosio016** [comment]
Fixed in https://github.com/RDambrosio016/RSLint/commit/77a7ea63b15790f06e20aa79ab3eff1d76d96f24

**Comment by brandly** [comment]
i pulled `master` to the latest (`f6f4cef`), ran `cargo install rslint_cli --force`, and i still see the same thing:

```shell
$ rslint_cli 'src/*.js'
error[]: The linter panicked unexpectedly. this is a bug.

We would appreciate a bug report: https://github.com/RDambrosio016/RSLint/issues/new?labels=ILE%2C+bug&template=internal-linter-error.md

note[]: Please include the following info: 

message: 
location: /Users/brandly/.cargo/registry/src/github.com-1ecc6299db9ec823/rslint_parser-0.1.2/src/parser.rs:158:9
```

am i doing something wrong?

**Comment by RDambrosio016** [comment]
cargo install would be pulling from crates.io, and the fixes are on an unreleased version

**Comment by RDambrosio016** [comment]
Other than a lot of imports spam it works for me if i use cargo run

**Comment by RDambrosio016** [comment]
@brandly i published new versions, it should work now if you install again

**Comment by brandly** [comment]
thanks!

> Other than a lot of imports spam it works for me if i use cargo run

you're right! this worked on my end too.

> cargo install would be pulling from crates.io

i was thinking the `cargo install` command was just building the local package and moving it to my PATH, similar to a [`stack install`](https://docs.haskellstack.org/en/stable/README/). makes sense tho!

**Comment by RDambrosio016** [comment]
`cargo install --path rslint_cli` can do that
